// Mocks generated by Mockito 5.4.6 from annotations
// in app_provedor_unified/test/core/services/diagnostico_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i6;
import 'dart:typed_data' as _i8;

import 'package:app_provedor_unified/core/services/diagnostico_service.dart'
    as _i18;
import 'package:app_provedor_unified/core/services/onu_wifi_service.dart'
    as _i3;
import 'package:battery_plus/battery_plus.dart' as _i9;
import 'package:battery_plus_platform_interface/battery_plus_platform_interface.dart'
    as _i10;
import 'package:connectivity_plus/connectivity_plus.dart' as _i12;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i13;
import 'package:dart_ping/dart_ping.dart' as _i4;
import 'package:flutter_internet_speed_test/flutter_internet_speed_test.dart'
    as _i15;
import 'package:flutter_internet_speed_test/src/flutter_internet_speed_test.dart'
    as _i16;
import 'package:flutter_internet_speed_test/src/flutter_internet_speed_test_platform_interface.dart'
    as _i17;
import 'package:http/http.dart' as _i2;
import 'package:lan_scanner/lan_scanner.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:network_info_plus/network_info_plus.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_2 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOnuData_3 extends _i1.SmartFake implements _i3.OnuData {
  _FakeOnuData_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePing_4 extends _i1.SmartFake implements _i4.Ping {
  _FakePing_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePingParser_5 extends _i1.SmartFake implements _i4.PingParser {
  _FakePingParser_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i8.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
      ) as _i5.Future<_i8.Uint8List>);

  @override
  _i5.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i5.Future<_i2.StreamedResponse>.value(_FakeStreamedResponse_1(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Battery].
///
/// See the documentation for Mockito's code generation for more information.
class MockBattery extends _i1.Mock implements _i9.Battery {
  MockBattery() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<int> get batteryLevel => (super.noSuchMethod(
        Invocation.getter(#batteryLevel),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> get isInBatterySaveMode => (super.noSuchMethod(
        Invocation.getter(#isInBatterySaveMode),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i10.BatteryState> get batteryState => (super.noSuchMethod(
        Invocation.getter(#batteryState),
        returnValue:
            _i5.Future<_i10.BatteryState>.value(_i10.BatteryState.full),
      ) as _i5.Future<_i10.BatteryState>);

  @override
  _i5.Stream<_i10.BatteryState> get onBatteryStateChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onBatteryStateChanged),
        returnValue: _i5.Stream<_i10.BatteryState>.empty(),
      ) as _i5.Stream<_i10.BatteryState>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i11.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String?> getWifiName() => (super.noSuchMethod(
        Invocation.method(
          #getWifiName,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getWifiBSSID() => (super.noSuchMethod(
        Invocation.method(
          #getWifiBSSID,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getWifiIP() => (super.noSuchMethod(
        Invocation.method(
          #getWifiIP,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getWifiIPv6() => (super.noSuchMethod(
        Invocation.method(
          #getWifiIPv6,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getWifiSubmask() => (super.noSuchMethod(
        Invocation.method(
          #getWifiSubmask,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getWifiGatewayIP() => (super.noSuchMethod(
        Invocation.method(
          #getWifiGatewayIP,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getWifiBroadcast() => (super.noSuchMethod(
        Invocation.method(
          #getWifiBroadcast,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i12.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i13.ConnectivityResult> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i5.Stream<_i13.ConnectivityResult>.empty(),
      ) as _i5.Stream<_i13.ConnectivityResult>);

  @override
  _i5.Future<_i13.ConnectivityResult> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i5.Future<_i13.ConnectivityResult>.value(
            _i13.ConnectivityResult.bluetooth),
      ) as _i5.Future<_i13.ConnectivityResult>);
}

/// A class which mocks [LanScanner].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanScanner extends _i1.Mock implements _i14.LanScanner {
  MockLanScanner() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get debugLogging => (super.noSuchMethod(
        Invocation.getter(#debugLogging),
        returnValue: false,
      ) as bool);

  @override
  bool get isScanInProgress => (super.noSuchMethod(
        Invocation.getter(#isScanInProgress),
        returnValue: false,
      ) as bool);

  @override
  set debugLogging(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #debugLogging,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Stream<_i14.Host> icmpScan(
    String? subnet, {
    int? firstIP = 1,
    int? lastIP = 255,
    int? scanThreads = 10,
    Duration? timeout = const Duration(seconds: 1),
    _i14.ProgressCallback? progressCallback,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #icmpScan,
          [subnet],
          {
            #firstIP: firstIP,
            #lastIP: lastIP,
            #scanThreads: scanThreads,
            #timeout: timeout,
            #progressCallback: progressCallback,
          },
        ),
        returnValue: _i5.Stream<_i14.Host>.empty(),
      ) as _i5.Stream<_i14.Host>);

  @override
  _i5.Future<List<_i14.Host>> quickIcmpScanSync(
    String? subnet, {
    int? firstIP = 1,
    int? lastIP = 255,
    Duration? timeout = const Duration(seconds: 1),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #quickIcmpScanSync,
          [subnet],
          {
            #firstIP: firstIP,
            #lastIP: lastIP,
            #timeout: timeout,
          },
        ),
        returnValue: _i5.Future<List<_i14.Host>>.value(<_i14.Host>[]),
      ) as _i5.Future<List<_i14.Host>>);

  @override
  _i5.Future<List<_i14.Host>> quickIcmpScanAsync(
    String? subnet, {
    int? firstIP = 1,
    int? lastIP = 255,
    Duration? timeout = const Duration(seconds: 1),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #quickIcmpScanAsync,
          [subnet],
          {
            #firstIP: firstIP,
            #lastIP: lastIP,
            #timeout: timeout,
          },
        ),
        returnValue: _i5.Future<List<_i14.Host>>.value(<_i14.Host>[]),
      ) as _i5.Future<List<_i14.Host>>);
}

/// A class which mocks [FlutterInternetSpeedTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterInternetSpeedTest extends _i1.Mock
    implements _i15.FlutterInternetSpeedTest {
  MockFlutterInternetSpeedTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLogEnabled => (super.noSuchMethod(
        Invocation.getter(#isLogEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool isTestInProgress() => (super.noSuchMethod(
        Invocation.method(
          #isTestInProgress,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> startTesting({
    required _i15.ResultCallback? onCompleted,
    _i16.DefaultCallback? onStarted,
    _i16.ResultCompletionCallback? onDownloadComplete,
    _i16.ResultCompletionCallback? onUploadComplete,
    _i15.TestProgressCallback? onProgress,
    _i16.DefaultCallback? onDefaultServerSelectionInProgress,
    _i16.DefaultServerSelectionCallback? onDefaultServerSelectionDone,
    _i17.ErrorCallback? onError,
    _i17.CancelCallback? onCancel,
    String? downloadTestServer,
    String? uploadTestServer,
    int? fileSizeInBytes = 10485760,
    bool? useFastApi = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startTesting,
          [],
          {
            #onCompleted: onCompleted,
            #onStarted: onStarted,
            #onDownloadComplete: onDownloadComplete,
            #onUploadComplete: onUploadComplete,
            #onProgress: onProgress,
            #onDefaultServerSelectionInProgress:
                onDefaultServerSelectionInProgress,
            #onDefaultServerSelectionDone: onDefaultServerSelectionDone,
            #onError: onError,
            #onCancel: onCancel,
            #downloadTestServer: downloadTestServer,
            #uploadTestServer: uploadTestServer,
            #fileSizeInBytes: fileSizeInBytes,
            #useFastApi: useFastApi,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void enableLog() => super.noSuchMethod(
        Invocation.method(
          #enableLog,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disableLog() => super.noSuchMethod(
        Invocation.method(
          #disableLog,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<bool> cancelTest() => (super.noSuchMethod(
        Invocation.method(
          #cancelTest,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [OnuWifiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnuWifiService extends _i1.Mock implements _i3.OnuWifiService {
  MockOnuWifiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiUrl => (super.noSuchMethod(
        Invocation.getter(#apiUrl),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#apiUrl),
        ),
      ) as String);

  @override
  String get cpfCnpj => (super.noSuchMethod(
        Invocation.getter(#cpfCnpj),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#cpfCnpj),
        ),
      ) as String);

  @override
  Map<String, String> get sgpParams => (super.noSuchMethod(
        Invocation.getter(#sgpParams),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_2(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  _i5.Future<_i3.OnuData> fetchOnuSignal() => (super.noSuchMethod(
        Invocation.method(
          #fetchOnuSignal,
          [],
        ),
        returnValue: _i5.Future<_i3.OnuData>.value(_FakeOnuData_3(
          this,
          Invocation.method(
            #fetchOnuSignal,
            [],
          ),
        )),
      ) as _i5.Future<_i3.OnuData>);

  @override
  _i5.Future<List<_i3.WifiNetwork>> fetchWifiNetworks() => (super.noSuchMethod(
        Invocation.method(
          #fetchWifiNetworks,
          [],
        ),
        returnValue:
            _i5.Future<List<_i3.WifiNetwork>>.value(<_i3.WifiNetwork>[]),
      ) as _i5.Future<List<_i3.WifiNetwork>>);

  @override
  _i5.Future<bool> updateWifi({
    required String? wifiId,
    required String? ssid,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWifi,
          [],
          {
            #wifiId: wifiId,
            #ssid: ssid,
            #password: password,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [PingFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockPingFactory extends _i1.Mock implements _i18.PingFactory {
  MockPingFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Ping create(
    String? host, {
    int? count,
    Duration? timeout,
    Duration? interval,
    bool? ipv6,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [host],
          {
            #count: count,
            #timeout: timeout,
            #interval: interval,
            #ipv6: ipv6,
          },
        ),
        returnValue: _FakePing_4(
          this,
          Invocation.method(
            #create,
            [host],
            {
              #count: count,
              #timeout: timeout,
              #interval: interval,
              #ipv6: ipv6,
            },
          ),
        ),
      ) as _i4.Ping);
}

/// A class which mocks [Ping].
///
/// See the documentation for Mockito's code generation for more information.
class MockPing extends _i1.Mock implements _i4.Ping {
  MockPing() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.PingParser get parser => (super.noSuchMethod(
        Invocation.getter(#parser),
        returnValue: _FakePingParser_5(
          this,
          Invocation.getter(#parser),
        ),
      ) as _i4.PingParser);

  @override
  String get command => (super.noSuchMethod(
        Invocation.getter(#command),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#command),
        ),
      ) as String);

  @override
  _i5.Stream<_i4.PingData> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i4.PingData>.empty(),
      ) as _i5.Stream<_i4.PingData>);

  @override
  set parser(_i4.PingParser? value) => super.noSuchMethod(
        Invocation.setter(
          #parser,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<bool> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
