import requests
import json
import time

API_KEY = "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"
BASE_URL = "https://openrouter.ai/api/v1/chat/completions"
HEADERS = {
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "HTTP-Referer": "https://painel-provedores.com",
    "X-Title": "Painel Provedores AI Orchestrator"
}

MODELS = {
    "DeepSeek": "tngtech/deepseek-r1t2-chimera:free",
    "Hermes": "nousresearch/hermes-3-llama-3.1-405b:free", 
    "Qwen": "qwen/qwen3-coder:free",
    "Mistral": "mistralai/devstral-2512:free",
    "Xiaomi": "xiaomi/mimo-v2-flash:free"
}

PROMPTS = {
    "DeepSeek": """
    You are the 'Insight Engine'. 
    Analyze modern 2025 mobile app design trends for FinTech and Utilities.
    Identify unique visual angles for these 4 specific concepts:
    1. Minimalist (Big Type)
    2. Futuristic (Clean transition)
    3. Dark Premium (Sophisticated)
    4. Dynamic Modular (Customizable)
    Return your answer in Markdown, bullet points only.
    """,
    
    "Hermes": """
    You are the 'Creative Director'.
    Based on modern trends, design 4 specific Layout Concepts for a Flutter App (Layout 12, 13, 14, 15).
    
    1. **Layout 12 (Minimalist)**: Focus on typography and large buttons.
    2. **Layout 13 (Futuristic)**: Clean, smooth transitions, interactive effects.
    3. **Layout 14 (Premium)**: Dark mode, sophisticated cards, gold/silver accents.
    4. **Layout 15 (Dynamic)**: Modular components, highly personalizable.
    
    For EACH, provide:
    - Primary/Secondary Colors (Hex codes).
    - Font Family suggestions (Google Fonts).
    - Button Shape (Rounded, Sharp, Pill).
    - Unique UI element description.
    Return your answer in Markdown.
    """,
    
    "Mistral": """
    You are the 'Functional Architect'.
    For the proposed layouts (12, 13, 14, 15), suggest FUNCTIONAL improvements.
    - Layout 12: How to make navigation intuitive with big buttons?
    - Layout 13: How to keep transitions performant?
    - Layout 14: How to organize data on sophisticated cards without clutter?
    - Layout 15: How to structure the modular grid code?
    Return your answer in Markdown.
    """,
    
    "Qwen": """
    You are the 'Tech Lead'.
    Provide specific Flutter implementations for these key components:
    1. **Layout 12**: A `BigButton` widget with large text.
    2. **Layout 13**: A `GlassCard` widget with blur.
    3. **Layout 14**: A `PremiumGradientCard` widget.
    4. **Layout 15**: A `ModularGrid` widget snippet.
    Provide DART code snippets.
    """,
    
    "Xiaomi": """
    You are the 'Rapid Prototyper'.
    Give 2 quick actionable tips for implementing these layouts faster in Flutter using standard packages.
    """
}

def query_model(name, model_id, prompt):
    print(f"🤖 Querying {name} ({model_id})...")
    try:
        data = {
            "model": model_id,
            "messages": [{"role": "user", "content": prompt}]
        }
        response = requests.post(BASE_URL, headers=HEADERS, data=json.dumps(data), timeout=60)
        
        if response.status_code != 200:
             print(f"⚠️ {name} failed: {response.text}")
             return f"## Input from {name}\n\n*Request Failed: {response.status_code}*\n\n---\n\n"

        result = response.json()
        content = result['choices'][0]['message']['content']
        print(f"✅ {name} responded.")
        return f"## Input from {name}\n\n{content}\n\n---\n\n"
    except Exception as e:
        print(f"❌ Error querying {name}: {e}")
        return f"## Input from {name}\n\n*Error: {e}*\n\n---\n\n"

def main():
    report = "# 🧠 AI Design Council Report\n\nGenerated by Gemini 3 Pro Orchestrator\n\n"
    
    # Execute sequentially to build context if we were passing it, but here we run in parallel conceptualy
    for agent, model_id in MODELS.items():
        if agent in PROMPTS:
            report += query_model(agent, model_id, PROMPTS[agent])
            time.sleep(1) # Polite delay
    
    # Save Report
    with open("docs/AI_DESIGN_REPORT.md", "w") as f:
        f.write(report)
    print("🚀 Report generated at docs/AI_DESIGN_REPORT.md")

if __name__ == "__main__":
    main()
