import type { ProviderConfig } from "@/shared/contracts";

export const DEFAULT_PROVIDER_CONFIG: ProviderConfig = {
  layoutType: "layout_06",
  themeColor: "#673AB7",
  secondaryColor: "#9575CD",
  backgroundColor: "#0A0E21",
  textColor: "#FFFFFF",
  textSecondaryColor: "#CBD5E1",
  invoiceColor: "#10B981",
  actionColor: "#E11D48",
  cardColor: "#F8F8F8",
  cardTextColor: "#333333",
  iconColor: "#673AB7",
  quickActionsCardColor: "#FFFFFF",
  quickActionsTextColor: "#333333",
  otherCardsColor: "#FFFFFF",
  otherCardsTextColor: "#333333",
  logoUrl: "",
  loginQuote: "Bem-vindo ao App do Assinante",
  typography: {
    fontFamily: "Inter",
    titleSize: "medium",
    bodySize: "medium",
    fontWeight: "medium",
  },
  strings: {
    hello_prefix: "Bem-vindo",
    plan_prefix: "Seu plano é:",
    logout_label: "Sair",
    home_tab_title: "Início",
    diagnostics_button: "Diagnóstico de Rede",
    status_ok_title: "Tudo certo",
    status_ok_message: "com seu(s) plano(s)!",
    select_contract_message: "Selecionar contrato",
    last_invoice_label: "Última fatura",
    view_invoices_label: "Ver faturas",
    pay_invoice_label: "Pagar fatura",
    promise_payment_label: "Prometer pagamento",
    support_title: "Suporte Técnico",
    channels_title: "Canais de Atendimento",
    open_ticket_title: "Abrir Novo Ticket",
    terms_title: "Termos de Serviço",
    ticket_subjects: ["Financeiro", "Suporte Técnico", "Comercial", "Outros"],
  },
  features: {
    consumption: true,
    support: true,
    invoices: true,
  },
  menuConfig: {
    order: ["invoices", "support", "contract"],
    items: {},
  },
  imageCarousel: [],
  faq: [],
  tips: [],
  supportContacts: [],
  supportChannels: [],
};

export const SENSITIVE_CONFIG_FIELDS = new Set([
  "integrations",
  "apiToken",
  "token",
  "password",
  "secret",
]);
