name: Proxy SGP CI

on:
  push:
    paths:
      - 'proxy-sgp/**'
  pull_request:
    paths:
      - 'proxy-sgp/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./proxy-sgp

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: './proxy-sgp/package-lock.json'

    - name: Install Dependencies
      run: npm ci || npm install

    - name: Syntax Check
      run: node -c index.js

    - name: Test Docker Build
      working-directory: ./
      run: docker compose build backend-proxy
